//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace conestogacinema_project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class movy
    {
        public movy()
        {
            this.showtimes = new HashSet<showtime>();
        }
    
        public int movie_id { get; set; }
        public string movie_title { get; set; }
        public string movie_description { get; set; }
        public int movie_runtime { get; set; }
        public System.DateTime movie_release_date { get; set; }
        public int genre_id { get; set; }
        public string imdb_id { get; set; }
        public string imdb_poster { get; set; }
    
        public virtual genre genre { get; set; }
        public virtual ICollection<showtime> showtimes { get; set; }
    }
}
