//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace conestogacinema_project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class room_types
    {
        public room_types()
        {
            this.rooms = new HashSet<room>();
        }
    
        public int type_id { get; set; }
        public string type_name { get; set; }
    
        public virtual ICollection<room> rooms { get; set; }
    }
}
