//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace conestogacinema_project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class showtime
    {
        public showtime()
        {
            this.AspNetUsers = new HashSet<AspNetUser>();
        }
    
        public int showtime_id { get; set; }
        public System.DateTime showtime_date { get; set; }
        public int movie_id { get; set; }
        public int room_id { get; set; }
        public string host_student_id { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual movy movy { get; set; }
        public virtual room room { get; set; }
        public virtual ICollection<AspNetUser> AspNetUsers { get; set; }
    }
}
